/**
 * SavedRelease Entity
 *
 * Represents a release that was automatically saved to a fan's Spotify library.
 * Domain entity with business logic and validation.
 */

export interface SavedReleaseProps {
  id: number;
  subscriptionId: string;
  releaseType: string;
  spotifyAlbumId: string;
  spotifyTrackIds: string[];
  albumName: string;
  releaseDate: Date;
  savedAt: Date;
  saveStatus: string;
  errorMessage?: string | null;
  createdAt: Date;
}

export class SavedRelease {
  private constructor(private readonly props: SavedReleaseProps) {
    this.validate();
  }

  private validate(): void {
    if (!this.props.spotifyAlbumId) {
      throw new Error('Spotify album ID is required');
    }
    if (!this.props.albumName) {
      throw new Error('Album name is required');
    }
    if (!['album', 'single', 'compilation'].includes(this.props.releaseType)) {
      throw new Error('Invalid release type');
    }
    if (!['success', 'failed', 'partial'].includes(this.props.saveStatus)) {
      throw new Error('Invalid save status');
    }
  }

  // Getters
  get id(): number {
    return this.props.id;
  }
  get subscriptionId(): string {
    return this.props.subscriptionId;
  }
  get releaseType(): string {
    return this.props.releaseType;
  }
  get spotifyAlbumId(): string {
    return this.props.spotifyAlbumId;
  }
  get spotifyTrackIds(): string[] {
    return this.props.spotifyTrackIds;
  }
  get albumName(): string {
    return this.props.albumName;
  }
  get releaseDate(): Date {
    return this.props.releaseDate;
  }
  get savedAt(): Date {
    return this.props.savedAt;
  }
  get saveStatus(): string {
    return this.props.saveStatus;
  }
  get errorMessage(): string | null | undefined {
    return this.props.errorMessage;
  }
  get createdAt(): Date {
    return this.props.createdAt;
  }

  /**
   * Check if save was successful
   */
  isSuccessful(): boolean {
    return this.props.saveStatus === 'success';
  }

  /**
   * Check if save failed
   */
  isFailed(): boolean {
    return this.props.saveStatus === 'failed';
  }

  /**
   * Create from database row
   */
  static fromDatabase(props: SavedReleaseProps): SavedRelease {
    return new SavedRelease(props);
  }

  /**
   * Create new saved release
   */
  static create(
    props: Omit<SavedReleaseProps, 'id' | 'savedAt' | 'createdAt'>
  ): SavedRelease {
    const now = new Date();
    return new SavedRelease({
      ...props,
      id: 0, // To be generated by DB
      savedAt: now,
      createdAt: now,
    });
  }
}
